### ISSUE TITLE
Zero-doc UI cleanup?

### ISSUE THREAD

**Issue by augustogoncalves** [augustogoncalves/bim360appstore-viewer-nodejs-visual.reports#5]
Consider cleanup the UI in zero-doc state: 
![image](https://user-images.githubusercontent.com/4291593/29786660-71344c82-8c02-11e7-8ca4-b1923e836d23.png)

**Comment by jaimerosales** [comment]
![screen shot 2017-08-30 at 3 33 47 pm](https://user-images.githubusercontent.com/8932722/29891322-aa96a8d4-8d98-11e7-8c3c-411dc2f94520.png)

**Comment by jaimerosales** [comment]
This is How it looks now at Initial State.

**Comment by augustogoncalves** [comment]
Why those gray boxes? Can you center (vertical middle) the sign in button?
